### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by Jaxingly** [AM-STUDIO/32-FUNCTION-BUTTON-BOX#3]
Hi so i decided to make a button box aswell and used your video as an instruction
I got stuck at the part where you upload your sketch 
See i've got the sane 5/5 grid as you (24 functions) but no rotary encoders ive got one selector switch instead with 12 functions
I was planning on using the other 8 functions that are left on my selector
I havent made a sketch myself because this is the first time for me using arduino 
I was wondering if there is a simple way to upload something like a preset from arduino? Or if you could make a 32 function sketch for me without rotary encoders? 
Please help me out
Mr. Green

**Comment by Jaxingly** [comment]
5/6 grid maybe

**Comment by madaz72** [comment]
hi can you get the sketch to upload?
