### ISSUE TITLE
'Joystick_' does not name a type

### ISSUE THREAD

**Issue by DantehZe** [AM-STUDIO/32-FUNCTION-BUTTON-BOX#5]
I get this error message from the sketch provided. Anyone able to help?

**Comment by SergioCarmo** [comment]
Hi, i think the problem is the joystick library. Check to see if you have the right one instaled




On Fri, May 17, 2019 at 2:20 AM +0100, "DantehZe" <notifications@github.com> wrote:












I get this error message from the sketch provided. Anyone able to help?

**Comment by MakerMike68** [comment]
Am having the same issue have tried other versions of Arduino  from 1.83 to the latest and get same error 

Pro Micro board 
Arduino IDE 1.89

'Joystick_' does not name a type
in the following line 
Joystick_ Joystick(JOYSTICK_DEFAULT_REPORT_ID, 
JOYSTICK_TYPE_JOYSTICK, 32, 0,
false, false, false, false, false, false,
false, false, false, false, false);

**Comment by MakerMike68** [comment]
OK found out it was the library but the program was looking at a different directory for the libraries not the /documents/arduino/libraries  but in my case it was in my root of my D: drive D:/arduino/libraries    if you read the error it should have the path for yours listed and make sure  the included libraries are in that location
