### ISSUE TITLE
Xbox / PS4 / Mac support

### ISSUE THREAD

**Issue by pikedave** [AM-STUDIO/32-FUNCTION-BUTTON-BOX#6]
Came across this a few days ago and made one. needed to make some changes to support the Xbox One X using keyboard support. I'd like to contribute the source to this project with the owners permission for those who may want to use this on a Mac, PS4 or Xbox. no need for JoyToKey on the PC with this version.

**Comment by SergioCarmo** [comment]
Hi, can you share the source plz.

**Comment by pikedave** [comment]
Sure, here's a link to the source
https://www.dropbox.com/s/lvb5hh4ab4o2eng/ARDUINO_BUTTON_BOXV3.ino?dl=0

**Comment by SergioCarmo** [comment]
Thank you!
 

Citando pikedave <notifications@github.com>:

> Sure, here's a link to the source
> https://www.dropbox.com/s/lvb5hh4ab4o2eng/ARDUINO_BUTTON_BOXV3.ino?dl=0
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].

 

Ligações:
---------
[1]  
https://github.com/AM-STUDIO/32-FUNCTION-BUTTON-BOX/issues/6?email_source=notifications&email_token=ALX6AA4W3CGLGYIDQP5E5OTP4C2IRA5CNFSM4H2OSS62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYMWSLI#issuecomment-504981805
[2]

**Comment by fernandoicecube** [comment]
hello.
congrats for this version of button box for xbox one
can some help me please. already bought the parts but a problem with code doesnt let me make the project work .

at sketch i have a problem and dont know hot to solve it
library issues, and already tryed many different libraries with out results

Arduino: 1.8.13 (Windows 10), Board: "Arduino Nano, ATmega328P"
C: \ Users \ ARDUINO_BUTTON_BOXV3 \ ARDUINO_BUTTON_BOXV3.ino: In function 'void CheckAllButtons ()':
ARDUINO_BUTTON_BOXV3: 114: 31: error: 'Keyboard' was not found. Does your draft include the line '#include <Keyboard.h>'?
                               Keyboard.press (buttbx.key [i] .kchar);
                               ^ ~~~~~~~
C: \ Users  \ ARDUINO_BUTTON_BOXV3 \ ARDUINO_BUTTON_BOXV3.ino: 114: 31: note: suggested alternative: 'Keypad'
                               Keyboard.press (buttbx.key [i] .kchar);
                               ^ ~~~~~~~
                               Keypad
C: \ Users \ ARDUINO_BUTTON_BOXV3 \ ARDUINO_BUTTON_BOXV3.ino: In function 'void CheckAllEncoders ()':
ARDUINO_BUTTON_BOXV3: 150: 7: error: 'Keyboard' was not found. Does your draft include the line '#include <Keyboard.h>'?
       Keyboard.press (rotarykeys [i] .ccwchar); delay (50); Keyboard.release (rotarykeys [i] .ccwchar);
       ^ ~~~~~~~
C: \ Users \ ARDUINO_BUTTON_BOXV3 \ ARDUINO_BUTTON_BOXV3.ino: 150: 7: note: suggested alternative: 'Keypad'
       Keyboard.press (rotarykeys [i] .ccwchar); delay (50); Keyboard.release (rotarykeys [i] .ccwchar);
       ^ ~~~~~~~
       Keypad
ARDUINO_BUTTON_BOXV3: 153: 7: error: 'Keyboard' was not found. Does your draft include the line '#include <Keyboard.h>'?
       Keyboard.press (rotarykeys [i] .cwchar); delay (50); Keyboard.release (rotarykeys [i] .cwchar);
       ^ ~~~~~~~
C: \ Users \ ARDUINO_BUTTON_BOXV3 \ ARDUINO_BUTTON_BOXV3.ino: 153: 7: note: suggested alternative: 'Keypad'
       Keyboard.press (rotarykeys [i] .cwchar); delay (50); Keyboard.release (rotarykeys [i] .cwchar);
       ^ ~~~~~~~
       Keypad
Multiple libraries were found for «Keypad.h»
Used: C: \ Program Files (x86) \ Arduino \ libraries \ libraries \ Keypad
Not used: C: \ Program Files (x86) \ Arduino \ libraries \ Keypad
Multiple libraries were found for «Keyboard.h»
Used: C: \ Program Files (x86) \ Arduino \ libraries \ libraries \ Keyboard
Not used: C: \ Program Files (x86) \ Arduino \ libraries \ libraries \ Keyboard-1.0.2
Not used: C: \ Program Files (x86) \ Arduino \ libraries \ Keyboard
exit status 1
'Keyboard' was not found. Does your draft include the line '#include <Keyboard.h>'?

Please, can someone tell me wich libraries are the correct ones and send me the link

thanks
