### ISSUE TITLE
keypad.h

### ISSUE THREAD

**Issue by tertug** [AM-STUDIO/32-FUNCTION-BUTTON-BOX#7]
hi,

where can i find keypad.h I couldn't find in your Joystick library or built in library

**Comment by AlBundy33** [comment]
see: https://forum.arduino.cc/index.php?topic=511429.0

**Comment by travmason** [comment]
For Keypad.h
In the IDE, sketch->include libraries->manage libraries.
In the searchbox at the top, type keypad
From the list, click the one by Mark Stanley and Alexaner Brevig
Click install
